
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "VS Code Guide",
    "author": "TheHamster",
    "url": "www.vscodeguides.com",
    "likes": 4
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "TheHamster",
    "likes": 4
}

###
DELETE http://localhost:3003/api/blogs/6066f79564c51931145532bc