
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "VS Code Guide",
    "author": "TheHamster",
    "url": "www.vscodeguides.com",
    "likes": 4
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "TheHamster",
    "likes": 4
}

###
DELETE http://localhost:3003/api/blogs/6066f79564c51931145532bc

###
PUT http://localhost:3003/api/blogs/6066e8482e7e3b20abe7d2b9
Content-Type: application/json

{
    "title": "VS Code Guide",
    "author": "TheHamster",
    "url": "www.vscodeguides.com",
    "likes": 7
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "alongCameZeus777",
    "name": "Brunhilde",
    "password": "superSecret"
}

###
DELETE http://localhost:3003/api/users/60671e5e1c43a91f8a546309

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hi",
    "name": "EpicMadam",
    "password": "superSecret"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "GreenTube",
    "name": "suppamaaio",
    "password": ""
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "GreenTube",
    "name": "suppamaaio",
    "password": "ja"
}